# Python circleci configuration file

version: 2
jobs: 
  build: 
    docker:
      - image: circleci/python3.7

    working_directory: ~/repo

    steps:
      # step 1: obtain repo from github
      - checkout
      # step 2: create virtual environment & install dependencies
      - run:
          name: install dependencies
          command:
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # step 3: run linter and tests
      - run:
          name: run tests            
          command:
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator